### ISSUE TITLE
Feature request: Configurable TLCP version

### ISSUE THREAD

**Issue by magkal** [Lightstreamer/Lightstreamer-lib-client-haxe#3]
Hi
I don't know how the underlying implementation works, but would it be possible to have the TLCP version configurable instead of hard coded, i can't connect to and older version of lightstreamer server but using the older dotnet version 5.1.8 with TLCP 2.1.0 works, but this library is connecting with 2.5.0 and results in version not supported for me.

Are there text protocol implementations that aren't backwards compatible in version 6.0.0 or could it be configurable to allow connection to slightly older lightstreamer servers?

**Comment by acarioni** [comment]
The TLCP version assures that a Client talks only to a Server compatible with it. For example the .NET Client 6 requires a server 7.4 and cannot work with older servers. 
If you have a server < 7.4, then you have to stick with the .NET Client 5.
